sudo: false

cache:
  apt: true
  directories:
    - ~/.stack

branches:
  only:
    - master
    - develop

before_install:
  - export PATH=/opt/ghc/$GHCVER/bin:$PATH
  - export PATH=~/.local/bin:$PATH
  - ./script/travis-lifecycle-before_install

install:
  - ./script/travis-lifecycle-install

script:
  - ./script/travis-lifecycle-script

matrix:
  fast_finish: true
  include:
    - env: GHCVER=8.0.1
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.3
      addons: { apt: { packages: [ghc-7.10.3], sources: [hvr-ghc] } }
