#!/usr/bin/env bash

set -e

GHCVER=${GHCVER?"GHCVER needs to be set."}

path=$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)

stack --no-terminal --skip-ghc-check --stack-yaml stack-$GHCVER.yaml test pagerduty
